
author: Guillaume Compagnon
email: gcompagnon@hotmail.com

layout: post
title: Asset and Assets
description: > # this means to ignore newlines until "show_exerpts:"
  Software | Computing | Project | Software | Engineer | Architecture | Innovation | Systems Integration | 
  Continuous Integration | Continuous Deployment | Continuous Delivery | Agile | Devops |
  C++ | C# | Java | Python | MultiThreading | Design Pattern | Commmando | Rapid Application Development |
  Regulatory Reporting | Transaction Reporting | RTS25 | MIFID2 | MIFID II | MIF2 | Solvency 2 | Sol2 | Basel III | US GAAP | IFRS
  Stock | Equity | Fixed Income | Asset Management | Swap | Interest Rate | Forex | Trading | Pricing | 
  PTP | NTP | Clock Synchronization | Low Latency | GPS |
  Derivative | Option | Future | American style Option | European style Option | 
  Market Data | Benchmark | Index | Indexes Asset Reallocation | Rebalancing | Drill Drown | Financial engineer |
  Risk Management | Delta | Alpha | Beta | Greeks| Tracking Error | VaR | Value at Risk | FRTB | expected shortfall | Stress Testing |
  Performance | Attribution | Allocation | Selection | Stock Picking | Total return | Scoring |
  CFA | AMF | ECB | Global Association of Risk Professionals | GARP | 
show_excerpts: true # set to true to show excerpts on the homepage
#baseurl: /


theme: minima

plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-mentions
- jekyll-paginate
- jekyll-gist
- jekyll-sitemap

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:

  date_format: "%Y-%m"

# generate social links in footer
  social_links:
      twitter: gcompagnon
      github: compagnon
      linkedin: compagnon
      rss: rss

jekyll-mentions:
  base_url: https://twitter.com

google_analytics: UA-119758867-1

repository: gcompagnon/gcompagnon.github.io

show_downloads: true

paginate: 4
paginate_path: "/posts/page:num/"

